In [72]:
import pandas as pd
import numpy as np
import gender_guesser.detector as guess

In [73]:
df = pd.read_csv(r"c:/Users/MARIA JOSE/Downloads/m_clinic.csv")

In [74]:
df['gender'] = df['gender'].replace(['u', ' '], np.nan)

In [75]:
# Guess the gender by the first name :)

g = guess.Detector()

def predict_gender(name):
    first_name = str(name).split()[0].capitalize()
    result = g.get_gender(first_name)

    if 'female' in result: 
        return 'Female'
    if 'male' in result: 
        return 'Male'
    return 'Unknown'
df['gender'] = df['patient_name'].apply(predict_gender)

In [76]:
print(df)

     patient_id       patient_name  age  gender appointment_date booking_date  \
0          1080     Tammy Williams   76  Female       2026-02-26   2024-12-03
1          1074   Megan Strickland   69  Female       2025-05-23   2024-06-12
2          1067   Amanda Schroeder   79  Female       2025-11-30   2024-08-05
3          1072  Anthony Mcpherson   47    Male       2025-05-18   2024-09-09
4          1092     Benjamin Brown   45    Male       2026-03-07   2024-08-17
..          ...                ...  ...     ...              ...          ...
995        1082       Thomas Roman   64    Male       2025-09-14   2024-07-15
996        1008        Jack Cooper   67    Male       2025-04-09   2024-06-20
997        1022  Christopher Brown   28    Male       2026-02-13   2024-06-13
998        1088   Michael Sullivan   65    Male       2025-07-04   2024-04-15
999        1003     Perry Crawford   79    Male       2025-11-05   2024-07-22

     days_between_dates              doctor   department currency  \
0                   450  Christopher Graham   Cardiology      GBP
1                   345       Brandon Lewis  Orthopedics      EUR
2                   482      Deanna Edwards    Neurology      EUR
3                   251       Karen Parsons      General      INR
4                   567    Andrea Hernandez      General      USD
..                  ...                 ...          ...      ...
995                 426         Robert Bass      General      INR
996                 293   Christopher Smith      General      INR
997                 610    Kimberly Johnson    Neurology      GBP
998                 445       Anthony Mccoy    Neurology      USD
999                 471        Marvin Hicks   Cardiology      EUR

     billing_amount follow_up_required
0            425.80                Yes
1            344.26                Yes
2            203.34                Yes
3             85.76                 No
4             84.44                Yes
..              ...                ...
995          200.43                Yes
996          244.49                 No
997          154.48                 No
998          434.95                 No
999          102.23                Yes

[1000 rows x 12 columns]

In [77]:
df.to_csv('c_clinic.csv', index = False)

In [80]:
pd.read_csv(r"c:/Users/MARIA JOSE/Documents/DATA ANALYST/PROJECTS/c_clinic.csv")

,patient_id,patient_name,age,gender,appointment_date,booking_date,days_between_dates,doctor,department,currency,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026-02-26,2024-12-03,450,Christopher Graham,Cardiology,GBP,425.80,Yes
1,1074,Megan Strickland,69,Female,2025-05-23,2024-06-12,345,Brandon Lewis,Orthopedics,EUR,344.26,Yes
2,1067,Amanda Schroeder,79,Female,2025-11-30,2024-08-05,482,Deanna Edwards,Neurology,EUR,203.34,Yes
3,1072,Anthony Mcpherson,47,Male,2025-05-18,2024-09-09,251,Karen Parsons,General,INR,85.76,No
4,1092,Benjamin Brown,45,Male,2026-03-07,2024-08-17,567,Andrea Hernandez,General,USD,84.44,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,Male,2025-09-14,2024-07-15,426,Robert Bass,General,INR,200.43,Yes
996,1008,Jack Cooper,67,Male,2025-04-09,2024-06-20,293,Christopher Smith,General,INR,244.49,No
997,1022,Christopher Brown,28,Male,2026-02-13,2024-06-13,610,Kimberly Johnson,Neurology,GBP,154.48,No
998,1088,Michael Sullivan,65,Male,2025-07-04,2024-04-15,445,Anthony Mccoy,Neurology,USD,434.95,No
999,1003,Perry Crawford,79,Male,2025-11-05,2024-07-22,471,Marvin Hicks,Cardiology,EUR,102.23,Yes

In [81]:
pd.read_csv(r"c:/Users/MARIA JOSE/Downloads/clean_clinic_dataset.csv")

,patient_id,patient_name,age,gender,appointment_date,booking_date,days_between_dates,doctor,department,currency,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026-02-26,2024-12-03,450,Christopher Graham,Cardiology,GBP,425.80,Yes
1,1074,Megan Strickland,69,Female,2025-05-23,2024-06-12,345,Brandon Lewis,Orthopedics,EUR,344.26,Yes
2,1067,Amanda Schroeder,79,Female,2025-11-30,2024-08-05,482,Deanna Edwards,Neurology,EUR,203.34,Yes
3,1072,Anthony Mcpherson,47,Male,2025-05-18,2024-09-09,251,Karen Parsons,General,INR,85.76,No
4,1092,Benjamin Brown,45,Male,2026-03-07,2024-08-17,567,Andrea Hernandez,General,USD,84.44,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1082,Thomas Roman,64,Male,2025-09-14,2024-07-15,426,Robert Bass,General,INR,200.43,Yes
996,1008,Jack Cooper,67,Male,2025-04-09,2024-06-20,293,Christopher Smith,General,INR,244.49,No
997,1022,Christopher Brown,28,Male,2026-02-13,2024-06-13,610,Kimberly Johnson,Neurology,GBP,154.48,No
998,1088,Michael Sullivan,65,Male,2025-07-04,2024-04-15,445,Anthony Mccoy,Neurology,USD,434.95,No
999,1003,Perry Crawford,79,Male,2025-11-05,2024-07-22,471,Marvin Hicks,Cardiology,EUR,102.23,Yes